name: Build Python Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build executable
      run: |
        # Commande PyInstaller avec tous les fichiers nécessaires
        pyinstaller --onefile ^
          --add-data "constants.py;." ^
          --add-data "feneire_jeu.py;." ^
          --add-data "feneire_question.py;." ^
          --add-data "styles.py;." ^
          --add-data "utils.py;." ^
          main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: application
        path: dist/main.exe
