name: Build and Release EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: executable
        path: dist/main.exe  # Adaptez selon le nom de votre exécutable

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4.2.1
      with:
        name: executable

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      with:
        tag_name: v0.0.${{ github.run_number }}
        name: Release v0.0.${{ github.run_number }}
        body: Automated release of the executable
        draft: false
        prerelease: false
        files: dist/main.exe  # Adaptez selon le nom de votre exécutable
      env:
        GITHUB_TOKEN: ${{ github.token }}
