name: Python Package using Conda

on: [push]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1.2.0
        with:
          python_ver: '3.8'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'main'
          options: --onefile
  
